<?php
include 'ldapConnection.php';

$fileds = ["name", "surname", "mail", "birthdate", "areaOfResidence", "password", "password_conf"];
foreach ($fileds as $value){
    if(!checkAttributes($_POST[$value])){
        header("Location: /register?error");
        exit();
    }
}
if($_POST["password"] != $_POST["password_conf"]){
    header("Location: /register?passError");
    exit();
}
$name = $_POST['name'];
$surname = $_POST['surname'];
$mail = $_POST['mail'];
$birthdate = $_POST['birthdate'];
$areaOfResidence = $_POST['areaOfResidence'];
$password = enc_password($_POST['password']);
$policyMakerID = (isset($_POST['policyMakerID']) && !empty($_POST['policyMakerID'])) ? $_POST['policyMakerID'] : null;

//VERIFY IF A USER EXISTS IN LDAP
$sr=ldap_search($ldapconn,$ldap['base_dn'],'(uid='.$mail.')');
$info = ldap_get_entries($ldapconn, $sr);
if($info['count']!==0) {
    header("Location: /register?error");
    exit();
}


//INSERT IN TEMPORARY DB AND SEND EMAIL
$db = new \mysqli("192.168.1.121", "se2group", "se2projectpassword", "dream_shibd");
$sql = "INSERT INTO pending_user (mail, name, surname, birthdate, areaOfResidence, password, policyMakerID, confirmationCode) VALUES (?,?,?,?,?,?,?,?)";
$token = bin2hex(openssl_random_pseudo_bytes(16));
while(!isFree($token, $db)){
    $token = bin2hex(openssl_random_pseudo_bytes(16));
}
$stmt = $db->prepare($sql);
$stmt->bind_param("ssssssss", $mail, $name, $surname, $birthdate, $areaOfResidence, $password, $policyMakerID, $token);
if($stmt->execute()){
    sendMail($mail, $token);
    header("Location: /confirm");
} else {
    header("Location: /confirm?evn_error");
}





function checkAttributes($attr){
    if(isset($attr) && !empty($attr)){
        return true;
    }
    return false;
}

function isFree($token, $db){
    $query = "SELECT 1 FROM pending_user WHERE confirmationCode=?";
    if ($stmt = $db->prepare($query)){
        $stmt->bind_param("s", $token);
        if($stmt->execute()){
            $result = $stmt->get_result();
            if($result->num_rows == 0){
                return true;
            }
        }
    }
    return false;
}

function enc_password($password){
    $ciphering = "AES-128-CTR";
    $iv_length = openssl_cipher_iv_length($ciphering);
    $options = 0;
    $encryption_iv = '1234567891011121';
    $encryption_key = "DreamShibbolethUserPassword";
    return openssl_encrypt($password, $ciphering,
        $encryption_key, $options, $encryption_iv);
}

function sendMail($to, $token){
    $subject = "Confirm Registration";

    $message = "
<html>
<head>
<title>Confirm Registration</title>
</head>
<body>
<p>To confirm your registration in dream IdP please click on the following link:</p>
<a href='https://auth.dreamplatform.it/confirm?confirmationCode=".$token."'>https://auth.dreamplatform.it/confirm?confirmationCode=".$token."</a><br/><br/>
<i>This message is autogenerated, please do not answer this email</i>
</body>
</html>
";

// Always set content-type when sending HTML email
    $headers = "MIME-Version: 1.0" . "\r\n";
    $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

// More headers
    $headers .= 'From: <noreply@auth.dreamplatform.it>' . "\r\n";

    mail($to, $subject, $message, $headers);

}

