<?php
include "ldapConnection.php";
$db = new \mysqli("192.168.1.121", "se2group", "se2projectpassword", "dream_shibd");
if(isset($_POST['email']) && !empty($_POST['email'])){
    $mail = $_POST['email'];
    $sr=ldap_search($ldapconn,$ldap['base_dn'],'(uid='.$mail.')');
    $info = ldap_get_entries($ldapconn, $sr);
    if($info['count']===0) {
        header("Location: /reset?error");
        exit();
    }


    $sql = "INSERT INTO pw_reset (mail, resetCode) VALUES (?,?)";
    $token = bin2hex(openssl_random_pseudo_bytes(16));
    while(!isFree($token, $db)){
        $token = bin2hex(openssl_random_pseudo_bytes(16));
    }
    $stmt = $db->prepare($sql);
    $stmt->bind_param("ss", $mail,  $token);
    if($stmt->execute()){
        sendMail($mail, $token);
        header("Location: /reset/confirm");
    } else {
        header("Location: /reset/confirm?evn_error");
    }
} else if(isset($_POST['resetCode']) && !empty($_POST['resetCode'])) {
    $resetCode = $_POST['resetCode'];
    $mail = getEmailByResetCode($resetCode, $db);
    if(is_null($mail)){
        header("Location: /reset/confirm?evn_error");
        exit();
    }
    if($_POST['new_password']!=$_POST['new_password_conf']){
        header("Location: /reset/confirm?evn_error&resetCode=".$resetCode);
        exit();
    }
    $password = ldapPassword($_POST['new_password']);
    //UPDATE LDAP AND REMOVE FROM DB
    $sr=ldap_search($ldapconn,$ldap['base_dn'],'(uid='.$mail.')');
    $info = ldap_get_entries($ldapconn, $sr);
    $dn=$info[0]["dn"];
    $userdata = array();
    $userdata["userPassword"][0]=$password;
    if(ldap_modify($ldapconn, $dn, $userdata)){
        $sql = "DELETE FROM pw_reset WHERE resetCode=?";
        $stmt = $db->prepare($sql);
        $stmt->bind_param("s", $resetCode);
        $stmt->execute();
        $stmt->close();

        header("Location: /reset/confirm?evn_success");
        exit();
    } else {
        header("Location: /reset/confirm?evn_error");
        exit();
    }

} else if(isset($_GET['resetCode']) && !empty($_GET['resetCode'])){
    //Control code validity
    if(!isFree($_GET['resetCode'], $db)) {
        include "views/passwordReset.php";
    } else {
        header("Location: /reset/confirm?evn_error");
    }
} else {
    header("Location: /reset/confirm?evn_error");
}


function getEmailByResetCode($restCode, $db){
    $sql = "SELECT mail FROM pw_reset WHERE resetCode=?";
    $stmt = $db->prepare($sql);
    $stmt->bind_param("s", $restCode);
    $stmt->execute();
    $result = $stmt->get_result();
    $stmt->close();
    if($result->num_rows == 0){
        return null;
    }
    $row = $result->fetch_assoc();
    return $row['mail'];
}

function isFree($token, $db){
    $query = "SELECT 1 FROM pw_reset WHERE resetCode=?";
    if ($stmt = $db->prepare($query)){
        $stmt->bind_param("s", $token);
        if($stmt->execute()){
            $result = $stmt->get_result();
            if($result->num_rows == 0){
                return true;
            }
        }
    }
    return false;
}

function sendMail($to, $token){
    $subject = "Password Reset";

    $message = "
<html>
<head>
<title>Password Reset</title>
</head>
<body>
<p>In order to reset your password please click of the following link:</p>
<a href='https://auth.dreamplatform.it/reset/confirm?resetCode=".$token."'>https://auth.dreamplatform.it/reset/confirm?resetCode=".$token."</a><br/><br/>
<i>This message is autogenerated, please do not answer this email</i>
</body>
</html>
";

// Always set content-type when sending HTML email
    $headers = "MIME-Version: 1.0" . "\r\n";
    $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

// More headers
    $headers .= 'From: <noreply@auth.dreamplatform.it>' . "\r\n";

    mail($to, $subject, $message, $headers);

}

function ldapPassword($password){
    mt_srand((double)microtime()*1000000);
    $salt = pack("CCCC", mt_rand(), mt_rand(), mt_rand(), mt_rand());
    $hash = "{SSHA}" . base64_encode(pack("H*", sha1($password . $salt)) . $salt);
    return $hash;
}