package it.dreamplatform.data.entity;

import javax.persistence.*;
import java.io.Serializable;

/**
 * This class represents the entity of an Administrator, mapped from the DB. The PRIMARY KEY, is the administratorId that is
 * also autogenerated. Then it contains all the attributes of the administrator table present in the DB.
 */
@Entity
@Table(name = "Administrator")
public class Administrator implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @Column(columnDefinition = "integer")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long administratorId;
    private String email;
    private String password;
    private String salt;

    public Long getAdministratorId() {
        return administratorId;
    }

    public void setAdministratorId(Long administratorId) {
        this.administratorId = administratorId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }
}
