package it.dreamplatform.data.entity;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Timestamp;

/**
 * This class represents the entity of a Data, mapped from the DB. The PRIMARY KEY, is the dataId that is
 * also autogenerated. Then it contains all the attributes of the Data table present in the DB. Some relevant attributes
 * are the longitude and latitude of the data and its value. Other two important attributes are the dataSourceId that
 * defines its dataSource and the district that define where the data is located.
 */
@Entity
@Table(name = "Data")
public class Data implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @Column(columnDefinition = "integer")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long dataId;
    private double value;
    private double longitude;
    private double latitude;
    private Timestamp timestamp;
    private Long dataSourceId;
    private String district;

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public Long getDataId() {
        return dataId;
    }

    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }

    public double getValue() {
        return value;
    }

    public void setValue(double value) {
        this.value = value;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public Timestamp getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public Long getDataSourceId() {
        return dataSourceId;
    }

    public void setDataSourceId(Long dataSourceId) {
        this.dataSourceId = dataSourceId;
    }
}
