package it.dreamplatform.data.entity;

import javax.persistence.*;
import java.io.Serializable;

/**
 * This class represents the entity of a DataSource, mapped from the DB. The PRIMARY KEY, is the dataSourceId that is
 * also autogenerated. Then it contains all the attributes of the DataSource table present in the DB.
 */
@Entity
@Table(name = "DataSource")
public class DataSource implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @Column(columnDefinition = "integer")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long dataSourceId;
    private String name;
    private String source;
    private String description;
    private Long dataTypeId;

    public Long getDataSourceId() {
        return dataSourceId;
    }

    public void setDataSourceId(Long dataSourceId) {
        this.dataSourceId = dataSourceId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getDataTypeId() {
        return dataTypeId;
    }

    public void setDataTypeId(Long dataTypeId) {
        this.dataTypeId = dataTypeId;
    }
}
