package it.dreamplatform.data.entity;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * This class represents the entity of a DataType, mapped from the DB. The PRIMARY KEY, is the dataTypeId that is also
 * autogenerated. The other element is the name of the area dataTpe.
 */
@Entity
@Table(name = "DataType")
public class DataType implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @Column(columnDefinition = "integer")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long dataTypeId;
    private String name;


    public Long getDataTypeId() {
        return dataTypeId;
    }

    public void setDataTypeId(Long dataTypeId) {
        this.dataTypeId = dataTypeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
