package it.dreamplatform.forum.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * This class represents the entity of a Discussion, mapped from the DB. The PRIMARY KEY, is the discussionId that is
 * also autogenerated. Then it contains all the attributes of the discussion table present in the DB. Two important
 * attributes are the topic attribute (@ManyToOne for having a bidirectional mapping from all the discussion to the
 * single topic that contains them all) and the posts attribute (@OneToMany for having a bidirectional mapping from
 * the single Discussion to the multiple posts that it contains).
 */
@Entity
@Table(name = "Discussion")
public class Discussion implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @Column(columnDefinition = "integer")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long discussionId;
    private String title;
    private String text;
    @Temporal(TemporalType.TIMESTAMP)
    private Date timestamp;

    @ManyToOne
    @JoinColumn(name = "topicId")
    private Topic topic;

    @OneToMany(mappedBy = "discussion", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Post> posts;


    public Long getDiscussionId() {
        return discussionId;
    }

    public void setDiscussionId(Long discussionId) {
        this.discussionId = discussionId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public Topic getTopic() {
        return topic;
    }

    public void setTopic(Topic topic) {
        this.topic = topic;
    }

    public List<Post> getPosts() {
        return posts;
    }

    public void setPosts(List<Post> posts) {this.posts = posts;}
}
