package it.dreamplatform.forum.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * This class represents the entity of a Post, mapped from the DB. The PRIMARY KEY, is the postId that is
 * also autogenerated. Then it contains all the attributes of the post table present in the DB. Two important
 * attributes are the creator attribute (@ManyToOne for having a unidirectional mapping from all the post to the
 * single user that has created them all) and the discussion attribute (@ManyToOne for having a bidirectional mapping
 * from all the post to the single discussion that contains them all).
 */
@Entity
@Table(name = "Post")
public class Post implements Serializable {
    @Id
    @Column(columnDefinition = "integer")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long postId;

    private String text;

    @Temporal(TemporalType.TIMESTAMP)
    private Date timestamp;

    private int status;

    @ManyToOne
    @JoinColumn(name = "creatorId")
    private User creator;

    @ManyToOne
    @JoinColumn(name = "discussionId")
    private Discussion discussion;


    public Long getPostId() {
        return postId;
    }

    public void setPostId(Long postId) {
        this.postId = postId;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public User getCreator() {
        return creator;
    }

    public void setCreator(User creator) {
        this.creator = creator;
    }

    public Discussion getDiscussion() {
        return discussion;
    }

    public void setDiscussion(Discussion discussion) {
        this.discussion = discussion;
    }
}